### ISSUE TITLE
Guard prevents format on save in `enh-ruby-mode`

### ISSUE THREAD

**Issue by re5et** [jimeh/rubocopfmt.el#2]
The guard here: https://github.com/jimeh/rubocopfmt.el/blob/master/rubocopfmt.el#L281 prevents this from running when using `enh-ruby-mode`.  Could you check for multiple modes:

```lisp
(when (member major-mode '(ruby-mode enh-ruby-mode)) (rubocopfmt))
```
or just see if it ends in `ruby-mode` or something that would allow this to work?

```lisp
(when (string-suffix-p (symbol-name major-mode) "ruby-mode") (rubocopfmt))
```

**Comment by jimeh** [comment]
@re5et thanks for the suggestion, and sorry I hadn't though about other major modes. I've now added a new `rubocopfmt-major-modes` customize option which defaults to `ruby-mode` and `enh-ruby-mode`. And obviously it lets you customize the list as you see fit.

If it turns out my changes don't quite fix your issue, please feel free to re-open this issue. For now I'm closing it though :)

**Comment by re5et** [comment]
fixed my issue and better solution than suggested :+1:
